name: CI

# Controls when the action will run.

on:

  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"

  android-release:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@main

      - name: Setup Android NDK

        uses: nttld/setup-ndk@main

        id: setup-ndk

        with:

          ndk-version: r21e

      - name: Setup Java JDK

        uses: actions/setup-java@main

        with:

          distribution: 'zulu'

          java-version: '11'

      - name: Setup Android SDK

        uses: android-actions/setup-android@main

      - name: Setup Haxe

        uses: krdlab/setup-haxe@master

        with:

          haxe-version: 4.2.5

      - name: Install Haxelibs

        run: |

          haxelib --quiet install lime 7.9.0

          haxelib --quiet install openfl 9.1.0

          haxelib --quiet install flixel

          haxelib --quiet --never run lime setup

          haxelib --quiet install flixel-ui

          haxelib --quiet install flixel-addons

          haxelib --quiet install polymod

          haxelib --quiet install hscript

          haxelib --quiet install hxcpp-debug-server

          haxelib --quiet git hxCodec https://github.com/polybiusproxy/hxCodec

          haxelib --quiet git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git

      - name: Setup Lime

        run: |

          haxelib run lime setup -alias -y

          haxelib run lime config ANDROID_SDK $ANDROID_HOME

          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME

          haxelib run lime config JAVA_HOME $JAVA_HOME

          haxelib run lime config ANDROID_SETUP true

          haxelib install actuate

          haxelib set lime 7.9.0

          haxelib set openfl 9.1.0

          haxelib list

        env:

          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile

        run: haxelib run lime build android -release

      - name: Publish Artifact

        uses: actions/upload-artifact@main

        with:

          name: androidBuild-release

          path: export/release/android/bin/app/build/outputs/apk/debug

  android-debug:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@main

      - name: Setup Android NDK

        uses: nttld/setup-ndk@main

        id: setup-ndk

        with:

          ndk-version: r21e

      - name: Setup Java JDK

        uses: actions/setup-java@main

        with:

          distribution: 'zulu'

          java-version: '11'

      - name: Setup Android SDK

        uses: android-actions/setup-android@main

      - name: Setup Haxe

        uses: krdlab/setup-haxe@master

        with:

          haxe-version: 4.2.5

      - name: Install Haxelibs

        run: |

          haxelib --quiet install lime 7.9.0

          haxelib --quiet install openfl 9.1.0

          haxelib --quiet install flixel

          haxelib --quiet --never run lime setup

          haxelib --quiet install flixel-ui

          haxelib --quiet install flixel-addons

          haxelib --quiet install polymod

          haxelib --quiet install hscript

          haxelib --quiet install hxcpp-debug-server

          haxelib --quiet git hxCodec https://github.com/polybiusproxy/hxCodec

          haxelib --quiet git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git

      - name: Setup Lime

        run: |

          haxelib run lime setup -alias -y

          haxelib run lime config ANDROID_SDK $ANDROID_HOME

          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME

          haxelib run lime config JAVA_HOME $JAVA_HOME

          haxelib run lime config ANDROID_SETUP true

          haxelib set lime 7.9.0

          haxelib set openfl 9.1.0

          haxelib list

        env:

          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile

        run: haxelib run lime build android -debug

      - name: Publish Artifact

        uses: actions/upload-artifact@main

        with:

          name: androidBuild-debug

          path: export/debug/android/bin/app/build/outputs/apk/debug
